services:
  vless-list:
    build: .
    restart: unless-stopped
    ports:
      - "5151:5151"
    environment:
      - PORT=5151
      - CHECK_INTERVAL=900
      - CONCURRENCY_LIMIT=10
      - MAX_PING_MS=1500
      - TIMEOUT_PING=5
      - EXTRA_VLESS_URL=${EXTRA_VLESS_URL}
    volumes:
      - ./vless-data:/app/vless-data
